spring:
  datasource:
    url: jdbc:mysql://192.168.10.100:5790/lsj_p?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: lsj_dev
    password: 6hdEN3u1A6iG0n%!