spring:
  datasource:
    url: jdbc:mysql://49.4.9.141:5790/lsj_p?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: lsj_dev
    password: 6hdEN3u1A6iG0n%!


#接管mybatis
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

test:
  ip: 2222